### ISSUE TITLE
Better behavior if not logged in

### ISSUE THREAD

**Issue by renky** [resellerinterface/api-client-php#2] opened 2022-04-11 16:06 UTC
If $client->login is missed and another request (e.g. handle/create) is called, it takes a huge time until "InvalidRequestException" with Curl-Error is thrown. 
```
ResellerInterface\Api\Exception\InvalidResponseException with message 'Curl-Error: Failed to connect to core-staging.resellerinterface.de port 443 after 133992 ms: Operation timed out'
```
Maybe the CURL-Timeout can be set to a lower value or even the API itself could come back much faster with the information "you are not logged in".

-----------
edit: seems to be a problem of the request handle/create
with domain/create everything works like expected - fast reponse, Not Logged In...

**Comment by henrikalves** [comment] 2022-05-31 07:09
Hi, unfortunately I can't reproduce the problem using the handle/create endpoint do you still have this issue?

**Comment by renky** [comment] 2022-05-31 13:00
seems to be fixed - maybe it was something on the api side

**Comment by henrikalves** [comment] 2022-05-31 13:08
cool then i will close this issue, feel free to make another issue if it happens again

**Closed as completed by henrikalves** 2022-05-31 13:08 UTC
